CREATE TABLE ticket (
  id BIGINT NOT NULL AUTO_INCREMENT,
  artist VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  account_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (account_id) REFERENCES account(id)
);